#!/usr/bin/env bash

if [[ $DISPLAY  ]]; then 
  x=$(printf "mpv\\nwget\\nfeh\\nbrowser\\nw3m" | dmenu -i -p "Open link with what program?")
  
  case "$x" in
    mpv) setsid mpv -quiet "$1" >/dev/null 2>&1 & ;;
    wget) wget "$1" >/dev/null 2>&1 ;;
    browser) xdg-open "$1" & ;;
    feh) setsid feh "$1" >/dev/null 2>&1 & ;;
    w3m) w3m "$1" ;;
  esac
else
  w3m "$1"
fi
