# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "sd_mod" "sr_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/2bca689b-a59d-47fd-90c6-8edc9039d222";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/0f1d5ccc-8090-4f69-823a-96d2f5772185";
      fsType = "ext4";
    };

  fileSystems."/hdd" =
    { device = "/dev/disk/by-uuid/b8530bcf-8ee1-4969-b1bc-e460bbf29b78";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."hdd".device = "/dev/disk/by-uuid/6d9fbce7-df17-4582-ad8b-3624b36b55ac";

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = "powersave";
}
